/**
 * article:hero-generation pipeline
 *
 * Standalone hero-image generation triggered from the UI.
 * Accepts an optional promptOverride so the user can review/edit the
 * outline's heroImagePrompt before committing to the Replicate call.
 *
 * Steps:
 *   1. GenerateHeroImageStep — loads outline from DB, generates via Replicate,
 *      persists heroImageR2Key/heroImagePublicUrl/heroImageAltText
 */
import { replicate } from "@marketing-auto/adapter-replicate";
import { COST_OPS } from "@marketing-auto/core/cost";
import { articles, db, projects } from "@marketing-auto/db";
import { createLogger } from "@marketing-auto/shared";
import { eq } from "drizzle-orm";
import { z } from "zod";
import { BaseStep, type StepContext } from "../../engine/step.ts";
import { Pipeline } from "../../engine/pipeline.ts";
import { ArticleOutlineSchema, ArticlePipelineError } from "../types.ts";

const log = createLogger("pipelines:hero-generation");

// ─── Step ────────────────────────────────────────────────────────────────────

const StepInputSchema = z.object({
  articleId: z.string().uuid(),
  projectId: z.string().uuid(),
  /** If provided, overrides outline.heroImagePrompt for this generation run. */
  promptOverride: z.string().optional(),
});

const StepOutputSchema = z.object({
  r2Key: z.string(),
  publicUrl: z.string(),
  altText: z.string(),
  promptUsed: z.string(),
});

class GenerateHeroImageStep extends BaseStep<
  z.infer<typeof StepInputSchema>,
  z.infer<typeof StepOutputSchema>
> {
  readonly name = "generate-hero-image";
  readonly inputSchema = StepInputSchema;
  readonly outputSchema = StepOutputSchema;

  override estimatedCostEur(): number {
    return 0.04; // Flux 1.1 Pro @ ~$0.04/image
  }

  async execute(input: z.infer<typeof StepInputSchema>, ctx: StepContext) {
    const [article] = await db
      .select({ outline: articles.outline, locale: articles.locale })
      .from(articles)
      .where(eq(articles.id, input.articleId))
      .limit(1);
    if (!article?.outline) throw new ArticlePipelineError("Article has no outline yet", "image");

    const outline = ArticleOutlineSchema.parse(article.outline);
    // Always append a centering directive so the subject survives the 4:3 and 1:1
    // crops generated by getSchemaImageVariants() for JSON-LD / OG image variants.
    const basePrompt = input.promptOverride?.trim() || outline.heroImagePrompt;
    const promptUsed = basePrompt.includes("centered")
      ? basePrompt
      : `${basePrompt}, subject centered, centered composition`;

    const [proj] = await db
      .select({ slug: projects.slug })
      .from(projects)
      .where(eq(projects.id, input.projectId))
      .limit(1);
    if (!proj) throw new ArticlePipelineError("Project not found", "image");

    const result = await replicate.generateImage({
      projectId: ctx.projectId,
      pipelineRunId: ctx.pipelineRunId,
      articleId: input.articleId,
      operation: COST_OPS.HERO_IMAGE,
      model: "flux-1.1-pro",
      prompt: promptUsed,
      aspectRatio: "16:9",
      storagePrefix: `${proj.slug}/articles/hero`,
      estimatedCostEur: this.estimatedCostEur(),
    });

    const altText =
      article.locale === "de"
        ? `${outline.title} – Beitragsbild`
        : `${outline.title} — ${promptUsed.slice(0, 100)}`;

    // Persist directly — this pipeline has no PersistArticleStep
    await db
      .update(articles)
      .set({
        heroImageR2Key: result.r2Key,
        heroImagePublicUrl: result.publicUrl,
        heroImageAltText: altText,
        updatedAt: new Date(),
      })
      .where(eq(articles.id, input.articleId));

    log.info(
      { articleId: input.articleId, r2Key: result.r2Key },
      "Hero image generated and saved"
    );

    return { r2Key: result.r2Key, publicUrl: result.publicUrl, altText, promptUsed };
  }
}

// ─── Pipeline ─────────────────────────────────────────────────────────────────

const InputSchema = z.object({
  articleId: z.string().uuid(),
  projectId: z.string().uuid(),
  promptOverride: z.string().optional(),
});

type PipelineInput = z.infer<typeof InputSchema>;

export class HeroImageGenerationPipeline extends Pipeline<PipelineInput, z.infer<typeof StepOutputSchema>> {
  readonly name = "article:hero-generation";
  readonly inputSchema = InputSchema;
  readonly outputSchema = StepOutputSchema;

  readonly steps = [new GenerateHeroImageStep()];
}
