import { z } from "zod";
import yaml from "yaml";
import { BaseStep, type StepContext } from "@marketing-auto/pipelines/engine";
import type { FrontmatterField } from "../types.ts";
import { createLogger } from "@marketing-auto/shared";

const log = createLogger("astro-sync:render");

const InputSchema = z.object({
  article: z.object({
    title: z.string(),
    slug: z.string(),
    metaDescription: z.string(),
    bodyMd: z.string(),
    cornerstoneKeyword: z.string(),
    heroImageAltText: z.string(),
    schemaJsonLd: z.array(z.record(z.unknown())),
    wordCount: z.number(),
  }),
  cluster: z.object({
    name: z.string(),
    pillar: z.string(),
  }).nullable(),
  collectionInfo: z.object({
    collectionName: z.literal("blog"),
    fields: z.array(z.object({
      name: z.string(),
      type: z.string(),
      required: z.boolean(),
      hasDefault: z.boolean(),
    })),
  }),
  heroAstroAssetPath: z.string(),
  astroRepoRoot: z.string(),
});

const OutputSchema = z.object({
  mdxPath: z.string(),
  mdxContent: z.string(),
  frontmatter: z.record(z.unknown()),
  unpopulatedRequired: z.array(z.string()),
});

const AUTO_GENERATED_HEADER = `<!--
  ⚠️  AUTO-GENERATED by Marketing Automation Platform.
      Source of truth: DB articles table.
      Manual edits will be overwritten on the next sync.
-->`;

export class RenderMdxStep extends BaseStep<
  z.infer<typeof InputSchema>,
  z.infer<typeof OutputSchema>
> {
  readonly name = "render-mdx";
  readonly inputSchema = InputSchema;
  readonly outputSchema = OutputSchema;

  override estimatedCostEur(): number { return 0; }

  async execute(input: z.infer<typeof InputSchema>, _ctx: StepContext) {
    const mdxPath = `${input.astroRepoRoot}/blog/${input.article.slug}.mdx`;
    const fm = buildFrontmatter(input);

    const unpopulatedRequired = input.collectionInfo.fields
      .filter((f) => f.required && !(f.name in fm))
      .map((f) => f.name);

    if (unpopulatedRequired.length > 0) {
      log.warn(
        { unpopulatedRequired },
        "Could not populate some required schema fields. " +
        "Astro build may fail. Add values via projects.astroFrontmatterDefaults.",
      );
    }

    const fmWithImagePaths = transformImageFields(
      fm,
      input.collectionInfo.fields as FrontmatterField[],
      mdxPath,
      input.heroAstroAssetPath,
    );

    const yamlBody = yaml.stringify(fmWithImagePaths, {
      lineWidth: -1,
      defaultStringType: "QUOTE_DOUBLE",
    }).trimEnd();

    const fullContent = [
      "---",
      yamlBody,
      "---",
      "",
      AUTO_GENERATED_HEADER,
      "",
      input.article.bodyMd.trim(),
      "",
    ].join("\n");

    return {
      mdxPath,
      mdxContent: fullContent,
      frontmatter: fmWithImagePaths,
      unpopulatedRequired,
    };
  }
}

function buildFrontmatter(input: z.infer<typeof InputSchema>): Record<string, unknown> {
  const today = new Date().toISOString().split("T")[0]!;
  const known: Record<string, unknown> = {
    title: input.article.title,
    description: input.article.metaDescription,
    slug: input.article.slug,
    publishDate: today,
    publishedAt: today,
    pubDate: today,
    updatedDate: today,
    heroImage: "<placeholder — replaced below>",
    heroImageAlt: input.article.heroImageAltText,
    cluster: input.cluster?.name ?? "",
    pillar: input.cluster?.pillar ?? "",
    cornerstoneKeyword: input.article.cornerstoneKeyword,
    wordCount: input.article.wordCount,
    schema: input.article.schemaJsonLd,
    schemaJsonLd: input.article.schemaJsonLd,
    tags: [] as string[],
    draft: false,
  };

  if (input.collectionInfo.fields.length === 0) {
    log.warn("Schema parse returned no fields; emitting permissive frontmatter");
    return known;
  }

  const fm: Record<string, unknown> = {};
  for (const field of input.collectionInfo.fields) {
    if (field.name in known) {
      fm[field.name] = known[field.name];
    }
  }
  return fm;
}

function transformImageFields(
  fm: Record<string, unknown>,
  fields: FrontmatterField[],
  mdxPath: string,
  assetPath: string,
): Record<string, unknown> {
  const out = { ...fm };
  const imageFieldNames = new Set(
    fields.filter((f) => f.type === "image").map((f) => f.name),
  );

  const heroImageCandidates = ["heroImage", "hero_image", "image", "cover"];
  if (imageFieldNames.size === 0) {
    for (const candidate of heroImageCandidates) {
      if (candidate in out) imageFieldNames.add(candidate);
    }
  }

  if (imageFieldNames.size === 0) return out;

  const relPath = computeRelative(mdxPath, assetPath);
  for (const name of imageFieldNames) {
    if (name in out) {
      out[name] = relPath;
    }
  }
  return out;
}

export function computeRelative(fromFile: string, toFile: string): string {
  const fromParts = fromFile.split("/").slice(0, -1);
  const toParts = toFile.split("/");
  let i = 0;
  while (i < fromParts.length && i < toParts.length && fromParts[i] === toParts[i]) i++;
  const upCount = fromParts.length - i;
  const ups = upCount === 0 ? "./" : "../".repeat(upCount);
  return ups + toParts.slice(i).join("/");
}
