import { astroFolderFor } from "@marketing-auto/content-schema/enums";
import { getDomainRegistry } from "@marketing-auto/pipelines/domain-registry";
import { BaseStep, type StepContext } from "@marketing-auto/pipelines/engine";
import { createLogger } from "@marketing-auto/shared";
import yaml from "yaml";
import { z } from "zod";
import { AstroSyncValidationError } from "../errors.ts";
import { validateFrontmatterAgainstSchema } from "../lib/validate-frontmatter.ts";
import type { FrontmatterField } from "../types.ts";

// Spec multi-domain-evolution S2.2: collection→Astro-folder lookup migrated to
// @marketing-auto/content-schema/enums. Pre-S2.2 this lived as a 4th copy of
// the same map under Pattern 107.

const log = createLogger("astro-sync:render");

const InputSchema = z.object({
  // Spec multi-domain-evolution Domain-Registry follow-up — projectId surfaced
  // so the boundary validator can resolve the tenant's DomainContext and
  // verify the target Astro folder is in the registered allow-list before
  // running the field-shape check.
  projectId: z.string().uuid(),
  article: z.object({
    // Spec multi-domain-evolution S1.2: id surfaced so AstroSyncValidationError
    // can carry the articleId in its payload for the S1.3 notification fan-out.
    id: z.string().uuid(),
    title: z.string(),
    slug: z.string(),
    metaDescription: z.string(),
    bodyMd: z.string(),
    cornerstoneKeyword: z.string().nullable().optional(),
    heroImageAltText: z.string(),
    schemaJsonLd: z.array(z.record(z.unknown())),
    wordCount: z.number(),
    domainExtras: z.record(z.unknown()).nullable().optional(),
    category: z.string().nullable().optional(),
    subcategory: z.string().nullable().optional(),
    tags: z.array(z.string()).nullable().optional(),
    author: z.string().nullable().optional(),
    intentType: z.string().nullable().optional(),
    locale: z.string().nullable().optional(),
    // Spec 61.1: collection type from DB, drives Astro content folder routing
    collectionType: z.string(),
  }),
  cluster: z
    .object({
      name: z.string(),
      pillar: z.string(),
    })
    .nullable(),
  collectionInfo: z.object({
    collectionName: z.string(),
    fields: z.array(
      z.object({
        name: z.string(),
        type: z.string(),
        required: z.boolean(),
        hasDefault: z.boolean(),
      })
    ),
  }),
  heroPublicPath: z.string(),
  astroRepoRoot: z.string(),
});

const OutputSchema = z.object({
  mdxPath: z.string(),
  mdxContent: z.string(),
  frontmatter: z.record(z.unknown()),
  unpopulatedRequired: z.array(z.string()),
});

// MDX does not support HTML comments (<!-- -->) — use JSX comment syntax instead.
const AUTO_GENERATED_HEADER = `{/*
  ⚠️  AUTO-GENERATED by Marketing Automation Platform.
      Source of truth: DB articles table.
      Manual edits will be overwritten on the next sync.
*/}`;

export class RenderMdxStep extends BaseStep<
  z.infer<typeof InputSchema>,
  z.infer<typeof OutputSchema>
> {
  readonly name = "render-mdx";
  readonly inputSchema = InputSchema;
  readonly outputSchema = OutputSchema;

  override estimatedCostEur(): number {
    return 0;
  }

  async execute(input: z.infer<typeof InputSchema>, _ctx: StepContext) {
    // Safe lookup: `astroFolderFor` returns the input unchanged for unknown
    // collections, so a future enum widening in @marketing-auto/content-schema
    // does not silently route into the wrong folder.
    const astroFolder = astroFolderFor(input.article.collectionType);

    // Spec multi-domain-evolution Domain-Registry follow-up — Facade gate.
    // Registry returns the tenant's DomainContext when the project's
    // `targetNiche` matches a registered DomainSpec; in that case, the Astro
    // folder MUST be in the spec's collection allow-list. When the registry
    // returns null (legacy project rows where targetNiche is missing OR a
    // niche whose DomainSpec isn't shipped yet), we fall back to the
    // Spec-50 JSONB validator alone — preserves zero-regression for any
    // Toolwiki-prior project. Note: `astroFolderFor` does folder-key
    // translation; the registry indexes by collection-key (the Drizzle
    // enum value, e.g. "comparison" not "comparisons"). For the lookup we
    // pass the raw `collectionType` so the comparison plural/singular
    // mismatch (Pattern documented in root CLAUDE.md) cannot bite.
    const domainCtx = await getDomainRegistry().forProject(input.projectId);
    if (domainCtx !== null) {
      const allowed = domainCtx.getAllowedCollections();
      if (!allowed.includes(input.article.collectionType)) {
        log.error(
          {
            articleId: input.article.id,
            projectId: input.projectId,
            niche: domainCtx.niche,
            collectionType: input.article.collectionType,
            astroFolder,
            allowed,
          },
          "[render-mdx] collection not in domain registry — refusing to write MDX",
        );
        throw new AstroSyncValidationError({
          articleId: input.article.id,
          collection: astroFolder,
          failures: [
            {
              fieldPath: "collection_type",
              expected: `one of [${allowed.join(", ")}]`,
              actual: input.article.collectionType,
              reason: "collection_not_in_registry",
            },
          ],
        });
      }
    }

    const mdxPath = `${input.astroRepoRoot}/${astroFolder}/${input.article.slug}.mdx`;
    const fm = buildFrontmatter(input);

    const fmWithImagePaths = transformImageFields(
      fm,
      input.collectionInfo.fields as FrontmatterField[],
      mdxPath,
      input.heroPublicPath
    );

    // Spec multi-domain-evolution S1.2: hard boundary validator. Replaces the
    // prior warn-only check on `unpopulatedRequired` and the silent-drop in
    // buildFrontmatter(). Closes L5 from the discovery doc: Tool writing a
    // field Astro Zod rejects → silent build drop → 404. Now throws
    // AstroSyncValidationError which S1.3 routes into a critical notification.
    const validation = validateFrontmatterAgainstSchema(
      fmWithImagePaths,
      input.collectionInfo.fields as FrontmatterField[],
    );
    if (!validation.success) {
      log.error(
        { articleId: input.article.id, collection: astroFolder, failures: validation.failures },
        "[render-mdx] boundary validation failed — refusing to write MDX",
      );
      throw new AstroSyncValidationError({
        articleId: input.article.id,
        collection: astroFolder,
        failures: validation.failures,
      });
    }
    // After a successful validation, no required field is missing by construction.
    const unpopulatedRequired: string[] = [];

    const yamlBody = yaml
      .stringify(fmWithImagePaths, {
        lineWidth: -1,
        defaultStringType: "QUOTE_DOUBLE",
      })
      .trimEnd();

    // Strip DOMAIN_EXTRAS marker — DraftStep embeds it at end of bodyMd;
    // MDX parser crashes on HTML comments (<!-- -->).
    // The LLM sometimes omits the closing "-->" so strip unconditionally to end-of-string
    // (the marker always appears last in the body by DraftStep convention).
    const strippedBody = input.article.bodyMd
      .replace(/\s*<!--\s*DOMAIN_EXTRAS:[\s\S]*/g, "")
      .trim();

    // Strip JSX component tags that have no import statement — the LLM occasionally
    // hallucinates <AuthorBox />, <ToolCard /> etc. which the MDX parser rejects.
    const cleanBody = sanitizeMdxComponents(strippedBody);

    const fullContent = [
      "---",
      yamlBody,
      "---",
      "",
      AUTO_GENERATED_HEADER,
      "",
      cleanBody,
      "",
    ].join("\n");

    return {
      mdxPath,
      mdxContent: fullContent,
      frontmatter: fmWithImagePaths,
      unpopulatedRequired,
    };
  }
}

function buildFrontmatter(input: z.infer<typeof InputSchema>): Record<string, unknown> {
  const today = new Date().toISOString().split("T")[0]!;
  const { article } = input;

  // Layer 1: LLM-generated extras (faq, seoTitle, seoDescription, bottomLinksVariant, etc.)
  const extras: Record<string, unknown> =
    article.domainExtras && typeof article.domainExtras === "object"
      ? { ...article.domainExtras }
      : {};

  // Layer 2: normalized DB columns (override extras — these are authoritative)
  const fromColumns: Record<string, unknown> = {};
  if (article.category) fromColumns.category = article.category;
  if (article.subcategory) fromColumns.subcategory = article.subcategory;
  if (article.tags?.length) fromColumns.tags = article.tags;
  if (article.author) fromColumns.author = article.author;
  if (article.intentType) fromColumns.intentType = article.intentType;

  // Derive readingTime from wordCount when not already in extras
  const wordsPerMin = 200;
  const readingMinutes = Math.max(1, Math.ceil((article.wordCount ?? 0) / wordsPerMin));
  const readingTime =
    extras.readingTime ??
    (article.locale === "de"
      ? `${readingMinutes} Min. Lesezeit`
      : `${readingMinutes} min read`);

  // Derive excerpt from seoDescription → seoTitle → metaDescription (in that priority)
  const excerpt =
    (extras.seoDescription as string | undefined) ??
    (extras.excerpt as string | undefined) ??
    article.metaDescription ??
    "";

  // Layer 3: static known fields (always win — highest priority)
  const known: Record<string, unknown> = {
    title: article.title,
    description: article.metaDescription,
    // seoTitle / seoDescription default to DB columns; extras can override with a shorter variant
    seoTitle: (extras.seoTitle as string | undefined) ?? article.title ?? "",
    seoDescription: (extras.seoDescription as string | undefined) ?? article.metaDescription ?? "",
    // Astro schema uses 'date' as the primary publish date field
    date: today,
    publishDate: today,
    publishedAt: today,
    pubDate: today,
    updatedDate: today,
    updated: today,
    heroImage: "<placeholder — replaced below>",
    heroImageAlt: article.heroImageAltText,
    cluster: input.cluster?.name ?? "",
    pillar: input.cluster?.pillar ?? "",
    cornerstoneKeyword: article.cornerstoneKeyword ?? "",
    wordCount: article.wordCount,
    schema: article.schemaJsonLd,
    schemaJsonLd: article.schemaJsonLd,
    draft: false,
    featured: false,
    speakable: true,
    readingTime,
    excerpt,
    // tags: prefer normalized column; fall back to extras; default to []
    tags: article.tags?.length ? article.tags : ((extras.tags as string[] | undefined) ?? []),
  };

  // Merged candidate map: extras < columns < known
  const merged: Record<string, unknown> = { ...extras, ...fromColumns, ...known };

  if (input.collectionInfo.fields.length === 0) {
    log.warn("Schema parse returned no fields; emitting permissive frontmatter");
    return merged;
  }

  const fm: Record<string, unknown> = {};
  for (const field of input.collectionInfo.fields) {
    if (field.name in merged) {
      fm[field.name] = merged[field.name];
    }
  }
  return fm;
}

function transformImageFields(
  fm: Record<string, unknown>,
  fields: FrontmatterField[],
  _mdxPath: string,
  heroPublicPath: string
): Record<string, unknown> {
  const out = { ...fm };
  const imageFieldNames = new Set(fields.filter((f) => f.type === "image").map((f) => f.name));

  const heroImageCandidates = ["heroImage", "hero_image", "image", "cover"];
  if (imageFieldNames.size === 0) {
    for (const candidate of heroImageCandidates) {
      if (candidate in out) imageFieldNames.add(candidate);
    }
  }

  if (imageFieldNames.size === 0) return out;

  // Hero images are served from public/gen/ as static files (not imported as Astro assets).
  // Use the public path directly (e.g. "/gen/<slug>/hero.webp") so Astro can resolve them
  // at runtime without needing a compile-time import. The collection schema must use
  // z.string() for the heroImage field — not image() — when using this approach.
  for (const name of imageFieldNames) {
    if (name in out) {
      out[name] = heroPublicPath;
    }
  }
  return out;
}

/**
 * Strips JSX component tags that appear in the body without a matching import.
 * The LLM occasionally hallucinates <AuthorBox />, <ToolCard />, etc.
 * Fenced code blocks are preserved unchanged.
 */
export function sanitizeMdxComponents(body: string): string {
  const imported = new Set<string>();
  for (const m of body.matchAll(/^import\s+(\w+)\s+from\s+['"][^'"]+['"]/gm)) {
    imported.add(m[1]!);
  }

  const codeBlocks: string[] = [];
  const withoutCode = body.replace(/```[\s\S]*?```/g, (match) => {
    codeBlocks.push(match);
    return `\x00CODE_BLOCK_${codeBlocks.length - 1}\x00`;
  });

  const sanitized = withoutCode.replace(
    /<([A-Z][a-zA-Z]*)([^>]*)\/?>[\s\S]*?<\/\1>|<([A-Z][a-zA-Z]*)([^>]*)\/>/g,
    (match, openTag, _attrs, selfTag) => {
      const name = openTag ?? selfTag;
      if (!name) return match;
      if (imported.has(name)) return match;
      return "";
    }
  );

  return sanitized.replace(/\x00CODE_BLOCK_(\d+)\x00/g, (_, idx) => codeBlocks[Number(idx)] ?? "");
}

export function computeRelative(fromFile: string, toFile: string): string {
  const fromParts = fromFile.split("/").slice(0, -1);
  const toParts = toFile.split("/");
  let i = 0;
  while (i < fromParts.length && i < toParts.length && fromParts[i] === toParts[i]) i++;
  const upCount = fromParts.length - i;
  const ups = upCount === 0 ? "./" : "../".repeat(upCount);
  return ups + toParts.slice(i).join("/");
}
