/**
 * Spec 65.5 — Shared LLM-brief-text builder for recurring-content briefs.
 *
 * Each format-type prepares its own user message (the format-specific
 * narrative framing) and hands it to `buildBriefText()` which:
 *   - Adds a small SEO/voice system prompt.
 *   - Calls Sonnet 4.6 for the free-text body (NOT jsonMode — Sonnet 4.6
 *     rejects assistant prefill per the root CLAUDE.md DO-NOT).
 *   - Returns `{ topicTitle, briefText }` parsed from a tagged-block format
 *     `<TITLE>...</TITLE>\n<BODY>...</BODY>` (same pattern as
 *     `TranslationBodyStep` per Pattern 109 in pipelines/CLAUDE.md).
 *
 * The brief text is consumed by the downstream `article:social-image` /
 * `article:blog` pipelines as the source-context fragment that primes the
 * LLM. It's NOT the final social-post copy — that's still generated by the
 * Remotion template's content-generation step at render time.
 */
import { anthropic } from "@marketing-auto/adapter-anthropic";
import { COST_OPS } from "@marketing-auto/core/cost";
import { createLogger } from "@marketing-auto/shared";

const log = createLogger("recurring-content:brief-text");

export interface BuildBriefTextInput {
  projectId: string;
  formatType: string;
  /** Human-readable description of the format (drives the prompt voice). */
  formatNarrative: string;
  /** Free-text context the LLM gets — tool descriptions, hook, framing. */
  contextBlock: string;
  /** Output locale — drives the `Output language:` instruction. */
  locale: "de" | "en";
  /** Propagated to Anthropic for cost-attribution. */
  pipelineRunId?: string;
}

export interface BuildBriefTextResult {
  topicTitle: string;
  briefText: string;
}

function parseBlock(raw: string, tag: string): string | null {
  const re = new RegExp(`<${tag}>([\\s\\S]*?)</${tag}>`, "i");
  const m = raw.match(re);
  if (!m) return null;
  return (m[1] ?? "").trim();
}

const SYSTEM_PROMPT = `You are an SEO-savvy social-media copy editor preparing brief context for a recurring social post. Output a short headline + 3-6 sentences of dense, factual brief text. No journalistic drama, no clickbait — your job is to set the angle for downstream content generators, not to write the final post. Respond with tagged blocks only.`;

export async function buildBriefText(input: BuildBriefTextInput): Promise<BuildBriefTextResult> {
  const localeLabel = input.locale === "de" ? "German (du-form)" : "English";
  const userMessage = [
    `Produce a brief for a "${input.formatType}" recurring post.`,
    "",
    `## Format narrative`,
    input.formatNarrative,
    "",
    `## Context`,
    input.contextBlock,
    "",
    `## Output rules`,
    `- Output language: ${localeLabel}`,
    `- Headline must be ≤ 90 characters, factual, SEO-driven (no drama tags / no "Schlacht" / no "Kampf um").`,
    `- Brief text: 3-6 sentences, dense and factual, primes downstream LLM for content generation.`,
    `- DO NOT write the final social-post copy — that's a different step.`,
    `- DO NOT add year tags ("2026:") unless the context explicitly carries a year.`,
    "",
    `Respond with exactly two tagged blocks:`,
    `<TITLE>headline</TITLE>`,
    `<BODY>brief text</BODY>`,
  ].join("\n");

  const result = await anthropic.messages({
    projectId: input.projectId,
    operation: COST_OPS.RECURRING_BRIEF_BUILD,
    model: "claude-sonnet-4-6",
    systemPrefix: SYSTEM_PROMPT,
    systemSuffix: "",
    userMessage,
    maxTokens: 800,
    estimatedCostEur: 0.05,
    ...(input.pipelineRunId !== undefined && { pipelineRunId: input.pipelineRunId }),
  });

  const title = parseBlock(result.raw, "TITLE");
  const body = parseBlock(result.raw, "BODY");
  if (title && body) {
    // Defensive: clamp the title to 200 chars in case the LLM ignored the
    // 90-char rule (we don't reject — Marcel can edit on review).
    return { topicTitle: title.slice(0, 200), briefText: body };
  }

  log.warn(
    { projectId: input.projectId, formatType: input.formatType },
    "buildBriefText: LLM output missing tagged blocks — falling back to raw",
  );
  // Defensive fallback — Marcel reviews briefs before they land as planned
  // items, so a malformed brief surfaces in the UI rather than crashing.
  const trimmed = result.raw.trim();
  return {
    topicTitle: trimmed.slice(0, 90),
    briefText: trimmed,
  };
}
