import { type SelfReviewIssue, articleVersions, articles, cornerstoneSpecs, db } from "@marketing-auto/db";
import { type ArticleCollectionType, ARTICLE_COLLECTION_TYPES } from "@marketing-auto/shared";
import { eq, sql } from "drizzle-orm";
import { z } from "zod";
import { BaseStep, type StepContext } from "../../engine/step.ts";

// Spec 61.2: mirror of COLLECTION_FOLDER in adapter-astro-sync — keeps the
// articles.collection (text) column aligned with the Astro folder routing.
// Separate map (not import) per Pattern 107: each concern owns its constant.
const COLLECTION_ASTRO_NAME: Record<ArticleCollectionType, string> = {
  blog: "blog",
  comparison: "comparisons",
  "ki-wissen": "ki-wissen",
  tools: "tools",
  usecases: "usecases",
};

const InputSchema = z.object({
  articleId: z.string().uuid(),
  bodyMd: z.string(),
  wordCount: z.number(),
  heroR2Key: z.string(),
  heroPublicUrl: z.string(), // may be empty when hero-image step was skipped
  heroAltText: z.string(),
  // Spec 64.6c: R2 key of the pre-conversion original (PNG/JPEG/etc.). NULL when
  // the producer returned WebP natively or the hero step was skipped. Forensic only
  // — no application reads it by default; useful for debugging Discovery #14.
  heroOriginalR2Key: z.string().nullable().optional(),
  selfReviewScore: z.number(),
  selfReviewIssues: z.array(z.unknown()),
  schemaJsonLd: z.record(z.unknown()),
  // Optional: set metadata when the pipeline provides them (e.g. translation)
  title: z.string().optional(),
  slug: z.string().optional(),
  metaDescription: z.string().optional(),
  category: z.string().optional(),
  subcategory: z.string().optional(),
  tags: z.array(z.string()).optional(),
  frontmatterExtras: z.record(z.unknown()).optional(),
  // Spec 61.1: collection type from pipeline input; defaults to 'blog' when absent
  collectionType: z.enum(ARTICLE_COLLECTION_TYPES).optional(),
});

const OutputSchema = z.object({
  articleId: z.string().uuid(),
  wordCount: z.number(),
  selfReviewScore: z.number(),
});

export class PersistArticleStep extends BaseStep<
  z.infer<typeof InputSchema>,
  z.infer<typeof OutputSchema>
> {
  readonly name = "persist-article";
  readonly inputSchema = InputSchema;
  readonly outputSchema = OutputSchema;

  override estimatedCostEur(): number {
    return 0;
  }

  async execute(input: z.infer<typeof InputSchema>, ctx: StepContext) {
    await db.transaction(async (tx) => {
      // Snapshot the existing draft as a version before overwriting (re-generation case).
      // First generation: bodyMd is empty/null — no snapshot needed.
      const [current] = await tx
        .select({ bodyMd: articles.bodyMd })
        .from(articles)
        .where(eq(articles.id, input.articleId))
        .limit(1);

      if (current?.bodyMd) {
        const versionRows = await tx
          .select({ nextVersion: sql<number>`COALESCE(MAX(version), 0) + 1` })
          .from(articleVersions)
          .where(eq(articleVersions.articleId, input.articleId));
        const nextVersion = versionRows[0]?.nextVersion ?? 1;

        await tx.insert(articleVersions).values({
          articleId: input.articleId,
          version: nextVersion,
          bodyMd: current.bodyMd,
          changeReason: `Re-generated by pipeline run ${ctx.pipelineRunId}`,
        });
      }

      await tx
        .update(articles)
        .set({
          bodyMd: input.bodyMd,
          wordCount: input.wordCount,
          heroImageR2Key: input.heroR2Key,
          heroImagePublicUrl: input.heroPublicUrl,
          heroImageAltText: input.heroAltText,
          // Spec 64.6c: persist forensic original R2 key only when present. We use
          // the conditional spread (rather than writing null/undefined directly) so
          // a hero-image step that skipped (returned no field) doesn't wipe an
          // existing column value on re-runs.
          ...(input.heroOriginalR2Key !== undefined && input.heroOriginalR2Key !== null
            ? { heroImageOriginalR2Key: input.heroOriginalR2Key }
            : {}),
          selfReviewScore: input.selfReviewScore,
          // Double-cast: InputSchema uses z.array(z.unknown()) so the bridge can pass issues
          // without re-validating. DB column uses its own SelfReviewIssue type which differs
          // structurally from Zod's inferred type under exactOptionalPropertyTypes (suggestion?: string).
          selfReviewIssues: input.selfReviewIssues as unknown as SelfReviewIssue[],
          // Spec 23: column is now Array — wrap the Article JSON-LD from AssemblyStep
          schemaJsonLd: [input.schemaJsonLd],
          status: "final_review",
          draftPipelineRunId: ctx.pipelineRunId,
          updatedAt: new Date(),
          lastRefreshedAt: new Date(),
          // Optional fields — only set when the calling pipeline provides them
          ...(input.title ? { title: input.title } : {}),
          ...(input.slug ? { slug: input.slug } : {}),
          ...(input.metaDescription ? { metaDescription: input.metaDescription } : {}),
          ...(input.category ? { category: input.category } : {}),
          ...(input.subcategory ? { subcategory: input.subcategory } : {}),
          ...(input.tags ? { tags: input.tags } : {}),
          ...(input.frontmatterExtras ? { frontmatterExtras: input.frontmatterExtras } : {}),
          // Spec 61.1: write collection type when provided by the pipeline
          // Spec 61.2: also align articles.collection (Astro folder text column) with the enum
          ...(input.collectionType
            ? {
                collectionType: input.collectionType,
                collection: COLLECTION_ASTRO_NAME[input.collectionType],
              }
            : {}),
        })
        .where(eq(articles.id, input.articleId));

      // If the article has a cornerstoneSpecId, mark spec as article_done
      const [art] = await tx
        .select({ specId: articles.cornerstoneSpecId })
        .from(articles)
        .where(eq(articles.id, input.articleId))
        .limit(1);
      if (art?.specId) {
        await tx
          .update(cornerstoneSpecs)
          .set({ status: "article_done", updatedAt: new Date() })
          .where(eq(cornerstoneSpecs.id, art.specId));
      }
    });

    return {
      articleId: input.articleId,
      wordCount: input.wordCount,
      selfReviewScore: input.selfReviewScore,
    };
  }
}
