import { type SelfReviewIssue, articleVersions, articles, cornerstoneSpecs, db } from "@marketing-auto/db";
import { eq, sql } from "drizzle-orm";
import { z } from "zod";
import { BaseStep, type StepContext } from "../../engine/step.ts";

const InputSchema = z.object({
  articleId: z.string().uuid(),
  bodyMd: z.string(),
  wordCount: z.number(),
  heroR2Key: z.string(),
  heroPublicUrl: z.string(), // may be empty when hero-image step was skipped
  heroAltText: z.string(),
  selfReviewScore: z.number(),
  selfReviewIssues: z.array(z.unknown()),
  schemaJsonLd: z.record(z.unknown()),
});

const OutputSchema = z.object({
  articleId: z.string().uuid(),
  wordCount: z.number(),
  selfReviewScore: z.number(),
});

export class PersistArticleStep extends BaseStep<
  z.infer<typeof InputSchema>,
  z.infer<typeof OutputSchema>
> {
  readonly name = "persist-article";
  readonly inputSchema = InputSchema;
  readonly outputSchema = OutputSchema;

  override estimatedCostEur(): number {
    return 0;
  }

  async execute(input: z.infer<typeof InputSchema>, ctx: StepContext) {
    await db.transaction(async (tx) => {
      // Snapshot the existing draft as a version before overwriting (re-generation case).
      // First generation: bodyMd is empty/null — no snapshot needed.
      const [current] = await tx
        .select({ bodyMd: articles.bodyMd })
        .from(articles)
        .where(eq(articles.id, input.articleId))
        .limit(1);

      if (current?.bodyMd) {
        const versionRows = await tx
          .select({ nextVersion: sql<number>`COALESCE(MAX(version), 0) + 1` })
          .from(articleVersions)
          .where(eq(articleVersions.articleId, input.articleId));
        const nextVersion = versionRows[0]?.nextVersion ?? 1;

        await tx.insert(articleVersions).values({
          articleId: input.articleId,
          version: nextVersion,
          bodyMd: current.bodyMd,
          changeReason: `Re-generated by pipeline run ${ctx.pipelineRunId}`,
        });
      }

      await tx
        .update(articles)
        .set({
          bodyMd: input.bodyMd,
          wordCount: input.wordCount,
          heroImageR2Key: input.heroR2Key,
          heroImagePublicUrl: input.heroPublicUrl,
          heroImageAltText: input.heroAltText,
          selfReviewScore: input.selfReviewScore,
          // Double-cast: InputSchema uses z.array(z.unknown()) so the bridge can pass issues
          // without re-validating. DB column uses its own SelfReviewIssue type which differs
          // structurally from Zod's inferred type under exactOptionalPropertyTypes (suggestion?: string).
          selfReviewIssues: input.selfReviewIssues as unknown as SelfReviewIssue[],
          // Spec 23: column is now Array — wrap the Article JSON-LD from AssemblyStep
          schemaJsonLd: [input.schemaJsonLd],
          status: "final_review",
          draftPipelineRunId: ctx.pipelineRunId,
          updatedAt: new Date(),
        })
        .where(eq(articles.id, input.articleId));

      // If the article has a cornerstoneSpecId, mark spec as article_done
      const [art] = await tx
        .select({ specId: articles.cornerstoneSpecId })
        .from(articles)
        .where(eq(articles.id, input.articleId))
        .limit(1);
      if (art?.specId) {
        await tx
          .update(cornerstoneSpecs)
          .set({ status: "article_done", updatedAt: new Date() })
          .where(eq(cornerstoneSpecs.id, art.specId));
      }
    });

    return {
      articleId: input.articleId,
      wordCount: input.wordCount,
      selfReviewScore: input.selfReviewScore,
    };
  }
}
